version: '3'

services:
  app:
    container_name: fitness-app
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/usr/src/app
  
  db:
    container_name: fitness-db
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitness